#!/bin/bash

echo "Enter the year: "
read YEAR
echo "Enter the day: "
read DAY

CURRENT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

echo "Creating $YEAR/day_$DAY"
mkdir -p "$YEAR/day_$DAY" && cd "$YEAR/day_$DAY"

touch test_input.txt
touch input.txt

echo "Enter the desired puzzle name: "
read FILENAME
echo "Enter the desired module name: "
read MODULENAME

PS3="Select the language: "
select lang in elixir crystal ruby; do

  case $lang in
    elixir)
      EXT=exs
      ;;
    crystal)
      EXT=cr
      ;;
    ruby)
      EXT=rb
      ;;
    quit)
      break
      ;;
    *)
      echo "Invalid option $REPLY"
      break
      ;;
  esac

  TESTMODULE="Test"
  cp "$CURRENT_DIR/templates/$lang/code.txt" $FILENAME.$EXT
  cp "$CURRENT_DIR/templates/$lang/test.txt" ${FILENAME}_test.$EXT
  sed -i '' "s/\$MODULE/$MODULENAME/g" *.$EXT
  sed -i '' "s/\$FILENAME/$FILENAME/g" *.$EXT
  echo "All set! Navigate to $YEAR/day_$DAY to get started!"
  break
done


